server:
  port: 8081
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
  #   discovery:
  #       health-check-path: /health
  application:
    name: todoService
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
  #spring.datasource.driver-class-username=com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ## Hibernate Properties
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

        ## This is important
        # Hibernate ddl auto (create, create-drop, validate, update)
        #spring.jpa.hibernate.ddl-auto = validate

        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: validate

# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
#         descriptor:
#           sql:
#             BasicBinder: TRACE
#         type: TRACE